version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compreface
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - compreface

  admin:
    image: exadel/compreface-admin:1.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/compreface
      POSTGRES_USER: postgres
      POSTGRES_DB: compreface
    ports:
      - "8001:8080"
    depends_on:
      - postgres
    networks:
      - compreface

  api:
    image: exadel/compreface-api:1.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/compreface
      POSTGRES_USER: postgres
      POSTGRES_DB: compreface
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - compreface

  fe:
    image: exadel/compreface-fe:1.2.0
    environment:
      REACT_APP_SERVER_URL: http://localhost:8000
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - compreface

  db-migrate:
    image: exadel/compreface-db-migrate:1.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgres:5432/compreface
      POSTGRES_USER: postgres
      POSTGRES_DB: compreface
    depends_on:
      - postgres
    networks:
      - compreface

volumes:
  postgres_data:

networks:
  compreface:
